@key = o32CV8I6fbp1K1FXWEpw 
 
 get https://www.goodreads.com/api/author_url/perumov?key={{key}}

##### search title, author, isbn (?q - search string, format - title, isbn, etc)
GET https://www.goodreads.com/search?key={{key}}&q=perumov
#-- return author id


### serch series by author id from prev request
GET https://www.goodreads.com/series/list?key={{key}}&id=711906

### get author info and books by id from prev req 
GET https://www.goodreads.com/author/show?key={{key}}&id=711906

### get info series by id from prev request
GET https://www.goodreads.com/series/show/80568?key={{key}}

### get gr id by isbn
GET https://www.goodreads.com/book/isbn_to_id?key={{key}}&isbn=isbn

### get rating by isbn (JSON!!!)
GET https://www.goodreads.com/book/review_counts.json?key={{key}}&isbns=0441172717,0141439602&format=json